name: worker
on:
  schedule:
    - cron: '0 */4 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  crawling:
    name: Crawling PTT
    runs-on: ubuntu-latest
    steps:
      - name: checkout maset
        uses: actions/checkout@v3

      - name: checkout runner
        uses: actions/checkout@v3
        with:
          ref: runner
      - run: |
          git config pull.rebase false
          git pull origin master

      - name: create queue
        run: |
          touch queue
          echo ${{ secrets.WORKS }} > queue

      - name: create .env
        run: |
          touch .env
          echo username=${{ secrets.USERNAME }} >> .env
          echo pw=${{ secrets.PASSWORD }} >> .env
          echo tg_bot_token=${{ secrets.TG_BOT_TOKEN }} >> .env
          echo tg_bot_chat_id=${{ secrets.TG_BOT_CHAT_ID }} >> .env

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
          python merge.py
          python main.py

      - name: clean files
        run: |
          rm .env
          rm queue

      - name: commit worker state
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push origin -d runner
          git push --set-upstream origin runner
